### ISSUE TITLE
container shows:  Syntax error: "(" unexpected`

### ISSUE THREAD

**Issue by jerryhopper** [jerryhopper/fusionauth_app_arm64#1]
@jerryhopper 

I am trying to replace the `botnyx/fusionauth-app-aarch64:latest` docker image with your `jerryhopper/fusionauth-app-arm64:latest` image but am getting the following error.

`/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh: 38: /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/setenv.sh: Syntax error: "(" unexpected`

_Originally posted by @arslanakhtar61 in https://github.com/FusionAuth/fusionauth-containers/issues/49#issuecomment-651679220_

**Comment by jerryhopper** [comment]
i've updated the build-script (https://github.com/jerryhopper/fusionauth_app_arm64/blob/master/buildscript.sh), which adds testing.   the buildscript is expected to be executed ARM devices ( Docker, JQ and curl )
the buildscript also flushes the docker cache, so everything is build fresh.

The build-test fails if there is no FA maintenance running after 20 seconds.

i have just build, tested and pushed the container. 

https://hub.docker.com/repository/docker/jerryhopper/fusionauth-app-arm64/general

**Comment by arslanakhtar61** [comment]
@jerryhopper. Thanks a lot. I just pulled the latest image and its working perfectly 👍.
